version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  backend:
    env_file:
      - ./backend/.env
    build:
      dockerfile: backend.Dockerfile
      context: backend/
    ports:
      - 3362:3362
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_URL: mongodb://root:example@mongo
    depends_on:
      - mongo
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

  ai-model:
    build:
      dockerfile: Dockerfile
      context: AI-Model/
    depends_on:
      - backend
    environment:
      VITE_EMPLOYEE_ENDPOINT: http://192.168.1.9:3362/v1/api/employees
      VITE_EMPLOYEE_IMG_ENDPOINT: http://192.168.1.9:3362/v1/api/employees/img
      VITE_STATUS_ENDPOINT: http://192.168.1.9:3362/v1/api/attendance
      VITE_ALL_ATTENDANCE_ENDPOINT: http://192.168.1.9:3362/v1/api/attendance
      VITE_ATTENDANCE_IMG_ENDPOINT: http://192.168.1.9:3362/v1/api/attendance/img
      VITE_DEVICES_ENDPOINT: http://192.168.1.9:3362/v1/api/devices
      VITE_NODE_SOCKET: http://192.168.1.9:3362

    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: "1.0"

  streaming:
    env_file:
      - ./streaming/.env
    build:
      dockerfile: streaming.Dockerfile
      context: streaming/
    ports:
      - 5580:5580
      - 9999:9999
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

  frontend:
    env_file:
      - ./frontend/.env
    build:
      dockerfile: frontend.Dockerfile
      context: frontend/
    ports:
      - 5173:5173
      - 5174:80
    environment:
      VITE_NODE_EMPLOYEES: http://192.168.1.9:3362/api/v1/employees
      VITE_NODE_CAMERAS: http://192.168.1.9:3362/api/v1/cameras
      VITE_NODE_ALERTS: http://192.168.1.9:3362/api/v1/alerts
      VITE_NODE_SOCKET: http://192.168.1.9:3362/
      VITE_NODE_STREAMING: ws://192.168.1.9:9999
      VITE_NODE_STREAMING_SERVER: http://192.168.1.9:5580
    depends_on:
      - backend
      - streaming
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

volumes:
  safesound:
